// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$UserModelImpl _$$UserModelImplFromJson(Map<String, dynamic> json) =>
    _$UserModelImpl(
      id: _readId(json, 'userId') as String,
      name: _readName(json, 'name') as String?,
      firstName: json['firstName'] as String?,
      lastName: json['lastName'] as String?,
      email: json['email'] as String?,
      username: json['profileName'] as String?,
      profileImage: json['imageUrl'] as String?,
      coverImage: json['coverImage'] as String?,
      userType: json['type'] as String?,
      bio: json['aboutMe'] as String?,
      country: json['country'] as String?,
      city: json['userLoc'] as String?,
      phone: json['mobile'] as String?,
      dob: json['dob'] as String?,
      isVerified: json['verified'] as bool? ?? false,
      isPrivate: json['isPrivate'] as bool? ?? false,
      isBlocked: json['isBlocked'] as bool? ?? false,
      policyAccepted: json['acceptPolicy'] as bool? ?? false,
      profile: json['profile'] as bool? ?? false,
      isPlayer: json['isPlayer'] as bool? ?? false,
      isCoach: json['isCoach'] as bool? ?? false,
      isAdmin: json['isAdmin'] as bool? ?? false,
      isFan: json['isFan'] as bool? ?? false,
      isReferee: json['isReferee'] as bool?,
      followersCount: (json['followCount'] as num?)?.toInt(),
      followingCount: (json['followingCount'] as num?)?.toInt(),
      matchesCount: (json['matchesCount'] as num?)?.toInt(),
      post: _readPost(json, 'post') as String? ?? '0',
      preferredPosition: json['playPosition'] as String?,
      nationality: json['nationality'] as String?,
      token: json['token'] as String?,
      sclId: json['sclId'] as String?,
      socialId: json['socialId'] as String?,
      media: json['media'] as String?,
      countryIso: json['countryIso'] as String?,
      countryCode: json['countryCode'] as String?,
      signUpTime: (json['signUpTime'] as num?)?.toInt(),
      lastOnline: (json['lastOnline'] as num?)?.toInt(),
      lastDevice: json['lastDevice'] as String?,
      autoverify: json['autoverify'] as bool? ?? false,
      verifyBadge: json['verifyBadge'] as bool? ?? false,
      ageGroup: json['ageGroup'] as String?,
      passKey: json['passKey'] as String?,
      deviceType: json['deviceType'] as String?,
      deviceId: json['deviceId'] as String?,
      deviceModel: json['deviceModel'] as String?,
      consentId: json['consentId'] as String?,
      isDelete: json['isDelete'] as bool? ?? false,
      postCount: (json['postCount'] as num?)?.toInt(),
      brands:
          (json['brands'] as List<dynamic>?)?.map((e) => e as String).toList(),
      fa: json['fa'] as String?,
      faName: json['faName'] as String?,
      gender: json['gender'] as String?,
      height: (json['height'] as num?)?.toInt(),
      isParentalConsent: json['isParentalConsent'] as bool? ?? false,
      jerseySize: json['jerseySize'] as String?,
      leagueFollow: json['leagueFollow'] as String?,
      nationalityIso: json['nationalityIso'] as String?,
      parentComment: (json['parentComment'] as num?)?.toInt(),
      parentLikeFollow: (json['parentLikeFollow'] as num?)?.toInt(),
      parentPhotoVideo: (json['parentPhotoVideo'] as num?)?.toInt(),
      parentPin: json['parentPin'] as String?,
      playLevel: json['playLevel'] as String?,
      playPositionType: json['playPositionType'] as String?,
      preferredFoot: json['preferredFoot'] as String?,
      preferredJersey: json['preferredJersey'] as String?,
      referByUserId: json['referByUserId'] as String?,
      referCode: json['referCode'] as String?,
      referId: json['referId'] as String?,
      registerCountry: json['registerCountry'] as String?,
      shoeSize: json['shoeSize'] as String?,
      shoeSizeUnit: json['shoeSizeUnit'] as String?,
      teamFollow: json['teamFollow'] as String?,
      university: json['university'] as String?,
      userLat: (json['userLat'] as num?)?.toDouble(),
      userLatLng: json['userLatLng'] as List<dynamic>?,
      userLng: (json['userLng'] as num?)?.toDouble(),
      acceptPolicyOn: (json['acceptPolicyOn'] as num?)?.toInt(),
      age: (json['age'] as num?)?.toInt(),
      lastUpdateDeviceModel: json['lastUpdateDeviceModel'] as String?,
      lastUpdateDeviceType: json['lastUpdateDeviceType'] as String?,
      lastUpdated: (json['lastUpdated'] as num?)?.toInt(),
      region: json['region'] as String?,
      endGoalkeeper: (json['endGoalkeeper'] as num?)?.toInt(),
      endMental: (json['endMental'] as num?)?.toInt(),
      endOverall: (json['endOverall'] as num?)?.toInt(),
      endPhysical: (json['endPhysical'] as num?)?.toInt(),
      endTechnical: (json['endTechnical'] as num?)?.toInt(),
      passChange: json['passChange'] as bool? ?? false,
      likeCount: (json['likeCount'] as num?)?.toInt(),
      tagVideos: json['tagVideos'] as List<dynamic>?,
    );

Map<String, dynamic> _$$UserModelImplToJson(_$UserModelImpl instance) =>
    <String, dynamic>{
      'userId': instance.id,
      'name': instance.name,
      'firstName': instance.firstName,
      'lastName': instance.lastName,
      'email': instance.email,
      'profileName': instance.username,
      'imageUrl': instance.profileImage,
      'coverImage': instance.coverImage,
      'type': instance.userType,
      'aboutMe': instance.bio,
      'country': instance.country,
      'userLoc': instance.city,
      'mobile': instance.phone,
      'dob': instance.dob,
      'verified': instance.isVerified,
      'isPrivate': instance.isPrivate,
      'isBlocked': instance.isBlocked,
      'acceptPolicy': instance.policyAccepted,
      'profile': instance.profile,
      'isPlayer': instance.isPlayer,
      'isCoach': instance.isCoach,
      'isAdmin': instance.isAdmin,
      'isFan': instance.isFan,
      'isReferee': instance.isReferee,
      'followCount': instance.followersCount,
      'followingCount': instance.followingCount,
      'matchesCount': instance.matchesCount,
      'post': instance.post,
      'playPosition': instance.preferredPosition,
      'nationality': instance.nationality,
      'token': instance.token,
      'sclId': instance.sclId,
      'socialId': instance.socialId,
      'media': instance.media,
      'countryIso': instance.countryIso,
      'countryCode': instance.countryCode,
      'signUpTime': instance.signUpTime,
      'lastOnline': instance.lastOnline,
      'lastDevice': instance.lastDevice,
      'autoverify': instance.autoverify,
      'verifyBadge': instance.verifyBadge,
      'ageGroup': instance.ageGroup,
      'passKey': instance.passKey,
      'deviceType': instance.deviceType,
      'deviceId': instance.deviceId,
      'deviceModel': instance.deviceModel,
      'consentId': instance.consentId,
      'isDelete': instance.isDelete,
      'postCount': instance.postCount,
      'brands': instance.brands,
      'fa': instance.fa,
      'faName': instance.faName,
      'gender': instance.gender,
      'height': instance.height,
      'isParentalConsent': instance.isParentalConsent,
      'jerseySize': instance.jerseySize,
      'leagueFollow': instance.leagueFollow,
      'nationalityIso': instance.nationalityIso,
      'parentComment': instance.parentComment,
      'parentLikeFollow': instance.parentLikeFollow,
      'parentPhotoVideo': instance.parentPhotoVideo,
      'parentPin': instance.parentPin,
      'playLevel': instance.playLevel,
      'playPositionType': instance.playPositionType,
      'preferredFoot': instance.preferredFoot,
      'preferredJersey': instance.preferredJersey,
      'referByUserId': instance.referByUserId,
      'referCode': instance.referCode,
      'referId': instance.referId,
      'registerCountry': instance.registerCountry,
      'shoeSize': instance.shoeSize,
      'shoeSizeUnit': instance.shoeSizeUnit,
      'teamFollow': instance.teamFollow,
      'university': instance.university,
      'userLat': instance.userLat,
      'userLatLng': instance.userLatLng,
      'userLng': instance.userLng,
      'acceptPolicyOn': instance.acceptPolicyOn,
      'age': instance.age,
      'lastUpdateDeviceModel': instance.lastUpdateDeviceModel,
      'lastUpdateDeviceType': instance.lastUpdateDeviceType,
      'lastUpdated': instance.lastUpdated,
      'region': instance.region,
      'endGoalkeeper': instance.endGoalkeeper,
      'endMental': instance.endMental,
      'endOverall': instance.endOverall,
      'endPhysical': instance.endPhysical,
      'endTechnical': instance.endTechnical,
      'passChange': instance.passChange,
      'likeCount': instance.likeCount,
      'tagVideos': instance.tagVideos,
    };

_$ClubUserModelImpl _$$ClubUserModelImplFromJson(Map<String, dynamic> json) =>
    _$ClubUserModelImpl(
      id: _readId(json, 'id') as String,
      clubName: _readStringFallback(json, 'clubName') as String,
      email: _readStringFallback(json, 'email') as String,
      logo: json['logo'] as String?,
      coverImage: json['coverImage'] as String?,
      country: json['country'] as String?,
      city: json['city'] as String?,
      bio: json['bio'] as String?,
      phone: json['phone'] as String?,
      token: json['token'] as String?,
      isVerified: json['isVerified'] as bool? ?? false,
      followersCount: (json['followersCount'] as num?)?.toInt(),
      subscriptionPlan: json['subscriptionPlan'] as String?,
    );

Map<String, dynamic> _$$ClubUserModelImplToJson(_$ClubUserModelImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'clubName': instance.clubName,
      'email': instance.email,
      'logo': instance.logo,
      'coverImage': instance.coverImage,
      'country': instance.country,
      'city': instance.city,
      'bio': instance.bio,
      'phone': instance.phone,
      'token': instance.token,
      'isVerified': instance.isVerified,
      'followersCount': instance.followersCount,
      'subscriptionPlan': instance.subscriptionPlan,
    };
